name: CatchBall
version: '${project.version}'
main: de.kadnick.catchball.CatchBall
api-version: 1.20
loadbefore:
  - SuperiorSkyblock2
commands:
  catchball:
    permission: catchball.admin.command.give
    description: main command