name: FangBall
version: '${project.version}'
main: de.tomstahlberg.fangball.FangBall
api-version: 1.20
softdepend:
  - SuperiorSkyblock2
commands:
  fangball:
    permission: fangball.admin.command.give
    description: main command